/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MiJFrame.java
 *
 * Created on 27-may-2010, 18:55:47
 */

package com.googlecode.jbridges.lib.interfaz;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;



/**
 *
 * @author MARIA
 */
public class Inicio extends javax.swing.JFrame {

   
    /** Creates new form MiJFrame */
    public Inicio() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comoJugar = new javax.swing.JButton();
        nuevaPartida = new javax.swing.JButton();
        cargarPartida = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HASHIWOKAKERO");
        setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        setName("incio"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 36));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HASHIWOKAKERO");

        comoJugar.setFont(new java.awt.Font("Croobie", 0, 18));
        comoJugar.setText("Cómo Jugar");
        comoJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comoJugarActionPerformed(evt);
            }
        });

        nuevaPartida.setFont(new java.awt.Font("Croobie", 0, 18));
        nuevaPartida.setText("Nueva Partida");
        nuevaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaPartidaActionPerformed(evt);
            }
        });

        cargarPartida.setFont(new java.awt.Font("Croobie", 0, 18));
        cargarPartida.setText("Cargar Partida");
        cargarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarPartidaActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Croobie", 0, 18));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nuevaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargarPartida))
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(comoJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(188, 188, 188))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(comoJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nuevaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cargarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaPartidaActionPerformed
        // TODO add your handling code here:
        Tamaño tam=new Tamaño(this, true);
        this.setVisible(false);
        tam.setLocationRelativeTo(null);
        tam.setVisible(true);
    }//GEN-LAST:event_nuevaPartidaActionPerformed

    private void comoJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comoJugarActionPerformed
         // TODO add your handling code here:
         Introduccion introduccion=new Introduccion(this, true);
         introduccion.setLocationRelativeTo(null);
         introduccion.setVisible(true);
    }//GEN-LAST:event_comoJugarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_salirActionPerformed

    private void cargarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarPartidaActionPerformed

         File archivo = null;
      FileReader fr = null;
      BufferedReader br = null;
      int anchoTablero;
      int altoTablero;
      int puntuacion;
      String[] solucion;
      String[] solucionUsuario;

      altoTablero = 0;
      puntuacion = 0;

      try {
         // Apertura del fichero y creacion de BufferedReader para poder
         // hacer una lectura comoda (disponer del metodo readLine()).
         archivo = new File ("C:\\partida.txt");
         fr = new FileReader (archivo);
         br = new BufferedReader(fr);

         // Lectura del fichero
         String linea;
         if ((linea=br.readLine())!=null) {
             String[] aux;
             aux = linea.split(":");
             anchoTablero = Integer.parseInt(aux[0]);
             altoTablero = Integer.parseInt(aux[1]);
         }

         if ((linea=br.readLine())!=null) {
            puntuacion = Integer.parseInt(linea);
         }

         if ((linea=br.readLine())!=null) {
            solucion = linea.split(":");
         }

         if ((linea=br.readLine())!=null) {
            solucionUsuario = linea.split(":");
         }

         switch (altoTablero) {
             case 7:
                TableroPequeño tableroPequeño = new TableroPequeño(puntuacion,1);
                tableroPequeño.setLocationRelativeTo(null);
                tableroPequeño.setVisible(true);
                this.setVisible(false);
                break;
             case 10:
                TableroMediano tableroMediano = new TableroMediano(puntuacion,1);
                tableroMediano.setLocationRelativeTo(null);
                tableroMediano.setVisible(true);
                this.setVisible(false);
                break;
             case 14:
                TableroGrande tableroGrande = new TableroGrande(puntuacion,1);
                tableroGrande.setLocationRelativeTo(null);
                tableroGrande.setVisible(true);
                this.setVisible(false);
                break;
             default:
         }
      }
      catch(Exception e){
         e.printStackTrace();
      }finally{
         // En el finally cerramos el fichero, para asegurarnos
         // que se cierra tanto si todo va bien como si salta
         // una excepcion.
         try{
            if( null != fr ){
               fr.close();
            }
         }catch (Exception e2){
            e2.printStackTrace();
         }
      }
    }//GEN-LAST:event_cargarPartidaActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inicio i=new Inicio();
                i.setLocationRelativeTo(null);
                i.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarPartida;
    private javax.swing.JButton comoJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nuevaPartida;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

}
