/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tamaño.java
 *
 * Created on 01-jun-2010, 18:12:41
 */

package com.googlecode.jbridges.lib.interfaz;

/**
 *
 * @author mdiazoli
 */
public class Tamaño extends javax.swing.JDialog {

    int puntuacion=0;
    /** Creates new form Tamaño */
    public Tamaño(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        buttonGroup1.add(pequeño);
        buttonGroup1.add(mediano);
        buttonGroup1.add(grande);
    }

    public Tamaño(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        buttonGroup1.add(pequeño);
        buttonGroup1.add(mediano);
        buttonGroup1.add(grande);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pequeño = new javax.swing.JRadioButton();
        mediano = new javax.swing.JRadioButton();
        grande = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tamaño");

        jLabel1.setFont(new java.awt.Font("Mufferaw", 1, 18));
        jLabel1.setText("Elija el tamaño del tablero:");

        pequeño.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18));
        pequeño.setText("Pequeño");
        pequeño.setName("baja"); // NOI18N
        pequeño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pequeñoActionPerformed(evt);
            }
        });

        mediano.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18));
        mediano.setText("Mediano");
        mediano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medianoActionPerformed(evt);
            }
        });

        grande.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18));
        grande.setText("Grande");
        grande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grandeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mediano)
                            .addComponent(pequeño)
                            .addComponent(grande))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(pequeño)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mediano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grande)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pequeño.getAccessibleContext().setAccessibleDescription("Baja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pequeñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pequeñoActionPerformed
        // TODO add your handling code here:
        puntuacion=puntuacion+20;
        Dificultad d=new Dificultad(this, true, 1, puntuacion);
        d.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_pequeñoActionPerformed

    private void medianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medianoActionPerformed
        // TODO add your handling code here:
        puntuacion=puntuacion+50;
        Dificultad d=new Dificultad(this, true, 2, puntuacion);
        d.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_medianoActionPerformed

    private void grandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grandeActionPerformed
        // TODO add your handling code here:
        puntuacion=puntuacion+75;
        Dificultad d=new Dificultad(this, true, 3, puntuacion);
        d.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_grandeActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tamaño dialog = new Tamaño(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton grande;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mediano;
    private javax.swing.JRadioButton pequeño;
    // End of variables declaration//GEN-END:variables

}
